name: Lesson 5 SAST

on:
  push:
    branches:
      - lesson-5
jobs:
  security_test:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    name: Execute the PyCharm security test
    steps:
      - uses: actions/checkout@v4
      - name: disable debug
        run: |
          sed -i 's/DEBUG = True/DEBUG = False/g' \
          hangry_api/hangry_api/settings.py
      - name: PyCharm Python Security Scanner
        uses: tonybaloney/pycharm-security@1.25.1
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest django_mock_queries six coverage
      - name: Unit Tests
        run: |
          coverage run -m --source=./hangry_api pytest
          coverage report
  deploy:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: "**PLACEHOLDER** Deploy to Elastic Beanstalk"
        run: echo Placeholder for Deployment
